version: '3'

services:

  filebot-node:
    container_name: filebot-node
    image: rednoah/filebot:node
    restart: unless-stopped
    volumes:
      - {{USER_HOME}}:/data:rw
      - {{RCLONE_DIR}}:/volume1/rclone/:rw
      - {{MEDIAS_DIR}}:/volume1/output/:rw
      - {{USER_HOME}}:{{USER_HOME}}
    ports:
      - 5452:5452
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
    networks:
      - monreseau

networks:
  docker-setup-reseau:
    driver: bridge
