version: '3'

services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true    
    environment:
      - TZ=Europe/Paris  
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}      
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}       
    restart: unless-stopped
    networks:
      - monreseau

networks:
  docker-setup-reseau:
    driver: bridge
