version: '3'

services:

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
      - VERSION=latest
    volumes:
      - {{APP_SETTINGS_DIR}}/overseerr:/config
      - {{USER_HOME}}:{{USER_HOME}}
    restart: unless-stopped
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
