version: '3'

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - VERSION=docker
      - PUID={{PUID}}
      - PGID={{PGID}}
      - PLEX_CLAIM={{PLEX_CLAIM}}
      - TZ=Europe/Paris
    ports:
      - 32400:32400
    volumes:
      - {{APP_SETTINGS_DIR}}/plex:/config
      - {{APP_SETTINGS_DIR}}/plex/transcode:/transcode
      - /mnt:/mnt
      - {{USER_HOME}}:{{USER_HOME}}
    restart: unless-stopped
    networks:
      - docker-setup-reseau

networks:
  docker-setup-reseau:
    driver: bridge
