version: '3'

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ce
    restart: unless-stopped
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - {{APP_SETTINGS_DIR}}/portainer:/data
      - {{USER_HOME}}:{{USER_HOME}}
    environment:
      - PUID={{PUID}}
      - PGID=101
      - TZ=Europe/Paris
    networks:
      - docker-setup-reseau

networks:
  docker-setup-reseau:
    driver: bridge
