version: '3'

services:

  rdtclient:
    container_name: rdtclient
    volumes:
      - '{{USER_HOME}}/seedbox/local:/data/downloads'
      - '{{APP_SETTINGS_DIR}}/rdt-client:/data/db' 
      - '/mnt/zurg:/mnt/zurg'
    image: laster13/rdtclient:latest
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - docker-setup-reseau

networks:
  docker-setup-reseau:
    driver: bridge

