version: '3'

services:

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID={{PUID}}
      - PGID={{PGID}}
      - TZ=Europe/Paris
    volumes:
      - {{APP_SETTINGS_DIR}}/sonarr:/config
      - {{USER_HOME}}:{{USER_HOME}}
      - {{LOCAL_DIR}}/sonarr:/data/downloads/sonarr
      - /mnt/zurg/torrents:/mnt/zurg/torrents
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - monreseau

networks:
  docker-setup-reseau:
    driver: bridge
