version: '3'

services:

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - {{USER_HOME}}:{{USER_HOME}}
    environment:
      TZ: "Europe/Paris"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_SCHEDULE: "0 0 4 * * *"
    networks:
      - docker-setup-reseau

networks:
  docker-setup-reseau:
    driver: bridge
