version: '3.8'

services:
  zurgfuse:
    image: ghcr.io/debridmediamanager/zurg-testing:v0-fuse
    container_name: zurgfuse
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - {{APP_SETTINGS_DIR}}/zurg/config.yml:/app/config.yml
      - {{APP_SETTINGS_DIR}}/zurg/zurgdata:/app/data
      - /mnt/zurg:/app/mnt:shared
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    command: mount -o attr_timeout=1.0 -o allow_other -o uid=1000 -o gid=1000 -o fsname=myawesomemount -o subtype=zurg -o atomic_o_trunc -o max_readahead=131072 -o default_permissions -o ro
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge