version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    container_name: zurg
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - {{APP_SETTINGS_DIR}}/zurg/config.yml:/app/config.yml
      - {{APP_SETTINGS_DIR}}/zurg/zurgdata:/app/data
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    networks:
      mon-reseau:
        ipv4_address: 172.18.0.14

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - PUID={{PUID}}
      - PGID={{PGID}}
    volumes:
      - /mnt/zurg:/data:rshared
      - {{USER_HOME}}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
    command: "mount zurg: /data --allow-non-empty --allow-other --uid={{PUID}} --gid={{PGID}} --dir-cache-time 10s --read-only"
    networks:
      - mon-reseau

networks:
  mon-reseau:
    driver: bridge
        
